site_name: CLARIN ERIC Operational Handbook
site_author: CLARIN ERIC sysops & developers
site_url: https://clarin-eric.github.io/handbook-operations
repo_url: https://github.com/clarin-eric/handbook-operations
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - content.action.view
    - content.action.edit
plugins:
  - search
markdown_extensions:
  - footnotes
  - tables
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.clarin.eu
    - icon: fontawesome/brands/github
      link: https://github.com/clarin-eric
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/CLARIN-ERIC
extra_css:
  - stylesheets/clarin-colours.css
      
nav:
  - 'Home': index.md
  - 'Provisioning': Provisioning.md
  - 'Container management': ContainerManagement.md
  - 'Security': Security.md
  - 'Logging': Logging.md
  - 'Monitoring': Monitoring.md
  - 'Incident handling': IncidentHandling.md
  - 'Analytics': Analytics.md
  - 'Deployment': Deployment.md
  - 'Observability': Observability.md
  - 'Infrastructure documentation': InfrastructureDocumentation.md
  - 'Code hosting and visibility': CodeHosting_Visibility.md
  - 'Maintenance': Maintenance.md
  - 'External hosting': ExternalHosting.md
