name: Markdown linting
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: install MDL
        run: gem install mdl -v 0.12.0
      - name: Lint README
        run: mdl README.md
      - name: Lint docs
        run: (cd docs && mdl .)
